### ISSUE TITLE
Article card formatting lost with Divi update

### ISSUE THREAD

**Issue by pixelxcode** [andyhqtran/Divi-100-Article-Card#25]
### Problem:
Formatting gone wrong after updating to Divi 2.7.6

### Steps To Reproduce:

1. Update to Divi 2.7.6

### Additional Information:

**Divi Version**: 2.7.6
<img width="365" alt="screen shot 2016-06-22 at 9 12 51 am" src="https://cloud.githubusercontent.com/assets/17263391/16251762/5e98286a-385b-11e6-9ac5-b40280834d73.png">

**Comment by erikgeurts** [comment]
I have also seen this happening.

Screen shot of an article card before upgrading Divi to 2.7.6:
*normal*
![image](https://cloud.githubusercontent.com/assets/5102461/16259275/1b0c29c8-3862-11e6-880b-46b488ab3cd5.png)
*hovered*
![image](https://cloud.githubusercontent.com/assets/5102461/16259251/fde3ba00-3861-11e6-9f0c-416f7b8c4062.png)

After upgrading to Divi 2.7.6:
*normal*
![image](https://cloud.githubusercontent.com/assets/5102461/16259351/8233c552-3862-11e6-8a2d-01e3256cbe66.png)
*hovered*
![image](https://cloud.githubusercontent.com/assets/5102461/16259370/9a34ddc6-3862-11e6-829e-132000c886b0.png)

That text you see is the Excerpt of the post (in my case). Since the only two options are to show either the content of the post or the excerpt, there is no way to fix this right now. other than fixing this plugin and/or Divi.

**Comment by targetburo** [comment]
Hi. I'm having the exact same issue with Article Cards, since the Divi update. I have the plugin currently disabled.

![captura de pantalla 2016-06-22 07 17 40](https://cloud.githubusercontent.com/assets/20090099/16266337/f01134ce-3849-11e6-9eda-bceb17974c99.png)

**Comment by pricciardi** [comment]
Same issue for me

**Comment by Wurzelwerk** [comment]
Same here!

**Comment by philsimon** [comment]
Thanks. I was unaware.

**Comment by guilamu** [comment]
Same here, it's totally broken.

**Comment by andyhqtran** [comment]
I'll be checking this out later today.
- [ ] Fixed article card compatibility

**Comment by christiwalk** [comment]
Ditto, I'm having the same problem. Article cards don't work since the update, please fix!!

**Comment by Fotogramatico** [comment]
Same here! for a moment i thought i broke the code with the CSS.

**Comment by guilamu** [comment]
You've been working on this for 13 hours straight now, is this impossible to fix?

**Comment by netbloger** [comment]
I have exactly the same issue after upgrading Divi to version 2.7.7

**Comment by andyhqtran** [comment]
Sorry everyone for the delay, I issue has been fixed in [702a756f8bfcc3a54c8477ca87b2ff138d802fb0](https://github.com/andyhqtran/Divi-100-Article-Card/commit/702a756f8bfcc3a54c8477ca87b2ff138d802fb0). Please let me know if there's anymore issues with it.

You can download the latest version [here](https://github.com/andyhqtran/Divi-100-Article-Card/releases/tag/v0.0.3).

**Comment by pricciardi** [comment]
The delay is more the normal for a free resource. Thaks so mutch for your free work.
Sorry for my english...
There is a litttle graphic problem with display of categories label.. but i cannot write the probleme because I dont know english.. i think that in a few miutes somewone will write it for me ;)

**Comment by andyhqtran** [comment]
Seems like this issue is fixed, closing for now. @pricciardi for the categories label bug, please create a new ticket thanks!

**Comment by erikgeurts** [comment]
Not only did this fix the issue, it actually improved the plugin, because now it shows the full excerpt when we hover over the article in the grid, instead of a shortened version:
![image](https://cloud.githubusercontent.com/assets/5102461/16330469/b9ce80fa-39e9-11e6-890a-f5cd9314bd15.png)

**Comment by christiwalk** [comment]
Thank you!!

**Comment by guilamu** [comment]
Well, it's nearly fixed, but now if the excerpt is too long, you can't even click on the title, so you can't access the article...

**Comment by erikgeurts** [comment]
Well, personally I would say the whole point of excerpts is to keep them short, and that would also automatically take care of this.

**Comment by guilamu** [comment]
Lengh of the excerpt change with the font.
